### ISSUE TITLE
Manual curation of renaming

### ISSUE THREAD

**Issue by ilsenatorov** [CATH-summer-2018/SFAM-renaming#5]
Hi guys, @andrabujan @Benjibump @fatima98crc

I created the list that is probably going to be final for renaming. The proposed changes are located in the [tsv file](https://github.com/CATH-summer-2018/SFAM-renaming/blob/master/results/renamed_superfamilies.tsv) and have the 4 columns - SFAM ID, old name, comment (changes implemented) and new name. If you could just take a look at the changes and comment on this issue about anything you find suspicious or bad - improper renamings etc etc.

One note though is that sometimes it appears as no changes has been made and comment states **R** - this is fine, usually it means that trailing whitespace has been removed.

**NB** comment codes can be found in the [README](https://github.com/CATH-summer-2018/SFAM-renaming/#comment-codes)

**Comment by ilsenatorov** [comment]
Especially if you could find any words that should be capitalised but are not because of the changes - names of organisms, surnames etc, that would be amazing!

**Comment by andrabujan** [comment]
Hi,

Just a few things that I spotted and would be nice to have them changed at one point:
- Uncharacterized to be changed to Uncharacterised (line 579 3.30.1860.10) and all sorts of American to British spelling - e.g. utilizing to utilising; line 86 1.10.472.60 disulfide to disulphide etc
- there are words like ATPase, GTPase, RNA etc. are at the moment uncapitalised (e.g. see line 6, 1.10.8.300; line 26, 1.10.40.50, line 117 1.10.1160.10)
- coa should be capitalised as CoA (see line 24, 1.10.12.10)
- c-terminal (or n-terminal) should have C and N capitalised (line 43, 1.10.220.100)
- line 130 1.10.3020.10 there is an unnecessary space after the "("
- there are many cases like this when the gene names or protein names should be/remain capitalised (first letter or all letters or first and last letters (depends - e.g. line 131 1.10.3030.10, line 57 1.10.287.800, line 59 1.10.287.870, line 89 1.10.533.10, line 107 1.10.880.10, line 149 1.10.3600.10, line 211 1.20.140.50, line 349 2.60.40.1670 etc etc etc)
- line 36 1.10.150.320 - kDa should remain capitalised like this
- line 103 1.10.750.10, line 604 3.40.50.410 - 'von' should not have been capitalised (special cases)
- line 264 2.20.28.20 - Zn should still be capitalised
- line 284 2.30.30.130 - Mu should remain capitalised
- line 326 2.40.310.10 - Barrel is still capitalised where it shouldn't 
- line 344 2.60.40.1580, line 426 3.10.290.20, line 605 3.40.50.700 - there should not be ":"
- line 393 2.102.10.10 - Fe and S should remain capitalised
- line 404 2.170.16.10 - Hint should remain capitalised
- line 480 3.30.70.1200 - Crispr to CRISPR
- line 503 3.30.310.10, line 697 3.90.210.10 - the letter after "-" still remains capitalised but in line 524 3.30.565.40 it is not
- line 765 4.10.470.10 - A should remain capitalised
I just added the cases that I thought might be representative for some issues.

Hope this helps!
